import {
  AlertCircle,
  Award,
  BookOpen,
  Building2,
  Calendar,
  CheckCircle,
  Clock,
  FileCheck,
  FileText,
  Globe,
  Mail,
  Medal,
  PenTool,
  Star,
  Target,
  Trophy,
  Users,
} from "lucide-react";

export const essayCompetitionPageContent = {
  prizes: [
    { position: "1st", amount: "K6,500", color: "from-yellow-400 to-yellow-600", textColor: "text-yellow-800", bg: "bg-yellow-50", border: "border-yellow-200", icon: Trophy, description: "Gold Medal + Certificate + Publication" },
    { position: "2nd", amount: "K5,500", color: "from-gray-300 to-gray-500", textColor: "text-gray-700", bg: "bg-gray-50", border: "border-gray-200", icon: Medal, description: "Silver Medal + Certificate + Publication" },
    { position: "3rd", amount: "K4,500", color: "from-orange-400 to-orange-600", textColor: "text-orange-800", bg: "bg-orange-50", border: "border-orange-200", icon: Medal, description: "Bronze Medal + Certificate + Publication" },
    { position: "4th", amount: "K3,500", color: "from-primary-400 to-primary-600", textColor: "text-primary-800", bg: "bg-primary-50", border: "border-primary-200", icon: Award, description: "Certificate + Publication" },
    { position: "5th", amount: "K2,500", color: "from-green-400 to-green-600", textColor: "text-green-800", bg: "bg-green-50", border: "border-green-200", icon: Award, description: "Certificate + Publication" },
  ],
  eligibility: [
    "Zambian nationals or residents enrolled in a recognised university or college",
    "Students studying in any discipline (science, arts, business, engineering, etc.)",
    "Must be registered full-time or part-time students at the time of submission",
    "Each student may submit only one essay",
    "The essay must be the original work of the student and not previously published",
    "Essays must be submitted in English",
  ],
  guidelines: [
    { label: "Word Count", value: "2,000 - 3,000 words (excluding references)", icon: FileText },
    { label: "Language", value: "English", icon: Globe },
    { label: "Format", value: "Microsoft Word (.docx) or PDF", icon: FileText },
    { label: "Font", value: "Times New Roman, 12pt, double-spaced", icon: PenTool },
    { label: "Citation Style", value: "Harvard Referencing System", icon: BookOpen },
    { label: "Submission", value: "Email to essays@zabs.org.zm", icon: Mail },
  ],
  timeline: [
    { date: "January 2026", event: "Competition Opens", desc: "Official announcement and guidelines released", status: "completed", icon: Calendar },
    { date: "31 March 2026", event: "Submission Deadline", desc: "All essays must be submitted by midnight", status: "active", icon: Clock },
    { date: "April 2026", event: "Judging Panel Review", desc: "Expert panel evaluates all submissions", status: "upcoming", icon: Users },
    { date: "May 2026", event: "Winners Announced", desc: "Results published on ZABS website and social media", status: "upcoming", icon: Trophy },
    { date: "June 2026", event: "Prize Giving Ceremony", desc: "Awards presented at ZABS annual Quality Awards event", status: "upcoming", icon: Award },
  ],
  pastWinners: [
    { year: "2024 (12th)", theme: "The Role of Standards in Sustainable Development", winner: "University of Zambia", student: "Maria Banda", place: "1st", abstract: "Explored how Zambian standards contribute to environmental sustainability and economic growth." },
    { year: "2023 (11th)", theme: "Standards and the Digital Economy", winner: "Copperbelt University", student: "John Phiri", place: "1st", abstract: "Analyzed the impact of ICT standards on Zambia's digital transformation journey." },
    { year: "2022 (10th)", theme: "Quality Infrastructure and COVID-19 Recovery", winner: "Mulungushi University", student: "Patricia Mwansa", place: "1st", abstract: "Examined the role of standards in building resilient health and economic systems." },
    { year: "2021 (9th)", theme: "Standards for Consumer Protection", winner: "University of Zambia", student: "David Mumba", place: "1st", abstract: "Investigated the effectiveness of compulsory standards in protecting Zambian consumers." },
  ],
  judgingCriteria: [
    { criterion: "Content & Relevance", weight: "30%", description: "Addresses the theme effectively with strong arguments" },
    { criterion: "Critical Analysis", weight: "25%", description: "Demonstrates analytical thinking and original insights" },
    { criterion: "Structure & Organisation", weight: "20%", description: "Logical flow, clear introduction, body, and conclusion" },
    { criterion: "Language & Style", weight: "15%", description: "Proper grammar, vocabulary, and academic tone" },
    { criterion: "Referencing", weight: "10%", description: "Correct citation format and appropriate sources" },
  ],
  stats: [
    { value: "13", label: "Annual Editions", sub: "Since 2012", icon: Trophy },
    { value: "2,500+", label: "Total Participants", sub: "To date", icon: Users },
    { value: "K65,000+", label: "Prize Money", sub: "Awarded to date", icon: Award },
    { value: "50+", label: "Universities", sub: "Represented", icon: BookOpen },
  ],
  faqItems: [
    { q: "Can I submit a co-authored essay?", a: "No. Essays must be the original work of a single author. Co-authored submissions will be disqualified." },
    { q: "Is there a registration fee?", a: "No. Participation in the ZABS Essay Competition is completely free." },
    { q: "Can I submit an essay that was written for a class?", a: "Yes, as long as it addresses the current theme and has not been previously published." },
    { q: "When will winners be announced?", a: "Winners will be announced in May 2026 on the ZABS website and social media channels." },
    { q: "Will I receive feedback on my essay?", a: "Due to the high volume of submissions, individual feedback is not provided." },
    { q: "Can international students apply?", a: "Yes, as long as you are enrolled in a recognised Zambian institution." },
  ],
  submissionAlertIcon: AlertCircle,
};

export const qualityAwardsPageContent = {
  awardCategories: [
    { name: "Large Business Category", desc: "For organisations with 100 or more employees. Recognises excellence in quality management, customer focus, leadership, and business results.", criteria: ["Leadership and Commitment", "Strategic Planning", "Customer Focus", "Measurement, Analysis & Improvement", "Workforce Engagement", "Operations Management", "Business Results"], icon: Building2, color: "primary", prize: "Trophy + Certificate + Marketing Package" },
    { name: "Small and Medium Enterprise (SME) Category", desc: "For organisations with fewer than 100 employees. Tailored assessment criteria recognising quality achievements relative to business size.", criteria: ["Management Commitment", "Customer Satisfaction", "Quality Processes", "Employee Involvement", "Continuous Improvement", "Business Performance"], icon: Users, color: "secondary", prize: "Trophy + Certificate + Development Support" },
    { name: "Public Service Category", desc: "For government ministries, departments, and agencies committed to improving service delivery and operational excellence.", criteria: ["Service Delivery", "Leadership", "Stakeholder Focus", "Resource Management", "Service Results", "Impact on Society"], icon: Target, color: "primary", prize: "Trophy + Certificate + Recognition Plaque" },
    { name: "Quality Champion Award", desc: "An individual recognition award for outstanding contributions to the promotion and advancement of quality in Zambia.", criteria: ["Personal contribution to quality", "Leadership in quality promotion", "Advocacy and awareness creation", "Mentorship and training", "Innovation in quality management"], icon: Star, color: "secondary", prize: "Medal + Certificate + Cash Prize" },
  ],
  benefits: [
    "National recognition and prestigious award trophy",
    "Use of the ZAQA Quality Award logo on marketing materials",
    "Feature in ZABS publications and media coverage",
    "Networking opportunities with quality leaders",
    "Access to benchmarking information and best practices",
    "Employee morale boost and stakeholder confidence",
  ],
  processSteps: [
    { step: "01", title: "Application", desc: "Submit your completed application form along with supporting documentation and the application fee.", icon: FileText, duration: "Week 1-2" },
    { step: "02", title: "Self-Assessment", desc: "Complete a comprehensive self-assessment questionnaire covering all assessment criteria.", icon: CheckCircle, duration: "Week 3-4" },
    { step: "03", title: "Document Review", desc: "ZAQA assessors review submitted documentation and score the application.", icon: FileCheck, duration: "Week 5-6" },
    { step: "04", title: "Site Visit", desc: "Shortlisted applicants receive an on-site assessment by a team of trained ZAQA assessors.", icon: Building2, duration: "Week 7-9" },
    { step: "05", title: "Consensus Meeting", desc: "Assessors hold a consensus meeting to finalise scores and recommendations.", icon: Users, duration: "Week 10" },
    { step: "06", title: "Awards Ceremony", desc: "Winners are announced and presented with their awards at the Annual Business Forum.", icon: Trophy, duration: "September" },
  ],
  pastWinners: [
    { year: "2024", category: "Large Business", winner: "Zambia Sugar Plc", industry: "Agriculture & Food Processing", description: "Exceptional implementation of quality management systems and sustainable practices." },
    { year: "2024", category: "SME Category", winner: "Mpongwe Milling", industry: "Food Manufacturing", description: "Outstanding quality improvements and community impact." },
    { year: "2024", category: "Public Service", winner: "Zambia Revenue Authority", industry: "Government Services", description: "Transformative service delivery improvements and digital innovation." },
    { year: "2024", category: "Quality Champion", winner: "Dr. Catherine Mwila", industry: "Quality Advocacy", description: "Lifetime achievement in quality promotion across Zambia." },
    { year: "2023", category: "Large Business", winner: "Chilanga Cement", industry: "Construction Materials", description: "Excellence in environmental management and product quality." },
    { year: "2023", category: "SME Category", winner: "Bio Food Products", industry: "Food Processing", description: "Innovation in food safety and quality assurance." },
    { year: "2023", category: "Public Service", winner: "National Health Insurance", industry: "Health Services", description: "Outstanding customer service and process improvement." },
  ],
  keyDates: [
    { date: "February 2026", event: "Applications Open", icon: Calendar, status: "upcoming" },
    { date: "30 April 2026", event: "Application Deadline", icon: Clock, status: "upcoming" },
    { date: "May - June 2026", event: "Document Review", icon: FileCheck, status: "upcoming" },
    { date: "July 2026", event: "Site Assessments", icon: Building2, status: "upcoming" },
    { date: "August 2026", event: "Consensus Meetings", icon: Users, status: "upcoming" },
    { date: "September 2026", event: "Awards Ceremony & Business Forum", icon: Trophy, status: "upcoming" },
  ],
  judgingCriteria: [
    { criterion: "Leadership", weight: "15%", description: "Demonstrated commitment to quality from top management" },
    { criterion: "Strategy", weight: "10%", description: "Strategic planning and deployment of quality initiatives" },
    { criterion: "Customer Focus", weight: "15%", description: "Understanding and meeting customer needs and expectations" },
    { criterion: "Measurement & Analysis", weight: "15%", description: "Data-driven decision making and performance measurement" },
    { criterion: "Workforce Engagement", weight: "10%", description: "Employee involvement in quality improvement" },
    { criterion: "Operations", weight: "15%", description: "Process management and operational efficiency" },
    { criterion: "Results", weight: "20%", description: "Business outcomes and quality achievements" },
  ],
  stats: [
    { value: "11", label: "Annual Editions", sub: "Since 2014", icon: Trophy },
    { value: "50+", label: "Award Recipients", sub: "To date", icon: Award },
    { value: "100+", label: "Applications", sub: "Annual average", icon: Users },
    { value: "95%", label: "Participant Satisfaction", sub: "2024 survey", icon: Star },
  ],
  programmeObjectives: [
    "Recognise excellence in quality management",
    "Promote best practices across Zambian industry",
    "Encourage continuous improvement",
    "Provide benchmarking opportunities",
    "Enhance national competitiveness",
  ],
  benefitStats: [
    { value: "100+", label: "Organisations", sub: "Assessed annually", icon: Building2 },
    { value: "50+", label: "Trained Assessors", sub: "Expert panel", icon: Users },
    { value: "K500K+", label: "Prize Value", sub: "Cash and in-kind", icon: Trophy },
    { value: "15+", label: "Industry Sectors", sub: "Represented", icon: Target },
  ],
};
