import { siteSettings } from "@/lib/content/site";
import type {
  ContactDepartment,
  ContactFaqItem,
  ContactOffice,
  ContactSocialItem,
  QuickStatItem,
} from "@/lib/content/types";

export const contactPageContent = {
  header: {
    title: "Contact Us",
    subtitle:
      "Reach out to ZABS for standards, certification, testing, training, and general enquiries",
    breadcrumbs: [{ label: "Contact Us" }],
    badge: "Get in Touch",
  },
  stats: [
    { value: "4", label: "Department Contacts", sub: "Direct lines", icon: "users" },
    { value: "3", label: "Office Locations", sub: "Nationwide", icon: "building2" },
    { value: "24/7", label: "Online Support", sub: "Email & web", icon: "headphones" },
    { value: "48h", label: "Response Time", sub: "Average", icon: "clock3" },
  ] satisfies QuickStatItem[],
  departmentsSection: {
    badge: "Direct Contacts",
    title: "Reach the Right Team",
    description: "Contact the appropriate department directly for faster assistance",
  },
  departments: [
    {
      icon: "bookOpen",
      name: "Standards",
      phone: "+260 777 764 420",
      phoneHref: "tel:+260777764420",
      email: "standards@zabs.org.zm",
      emailHref: "mailto:standards@zabs.org.zm",
      description: "Standards development, publication, and sales enquiries.",
      hours: "Mon-Fri: 08:00 - 17:00",
      color: "primary",
    },
    {
      icon: "award",
      name: "Certification & Training",
      phone: "+260 777 764 421",
      phoneHref: "tel:+260777764421",
      email: "certification@zabs.org.zm",
      emailHref: "mailto:certification@zabs.org.zm",
      description: "Product certification, management system certification, and training registration.",
      hours: "Mon-Fri: 08:00 - 17:00",
      color: "secondary",
    },
    {
      icon: "building2",
      name: "Communications",
      phone: "+260 777 764 422",
      phoneHref: "tel:+260777764422",
      email: "communications@zabs.org.zm",
      emailHref: "mailto:communications@zabs.org.zm",
      description: "Media relations, partnerships, and general communications.",
      hours: "Mon-Fri: 08:00 - 17:00",
      color: "primary",
    },
    {
      icon: "beaker",
      name: "Testing Laboratories",
      phone: "+260 777 764 423",
      phoneHref: "tel:+260777764423",
      email: "testing@zabs.org.zm",
      emailHref: "mailto:testing@zabs.org.zm",
      description: "Laboratory testing services, test requests, and results.",
      hours: "Mon-Fri: 08:00 - 17:00",
      color: "secondary",
    },
  ] satisfies ContactDepartment[],
  officesSection: {
    badge: "Our Locations",
    title: "Visit Our Offices",
    description: "Three convenient locations serving Zambia",
  },
  offices: [
    {
      name: "Head Office - Lusaka",
      address: "Lechwe House, Freedom Way, Lusaka",
      pobox: "P.O. Box 31302, Lusaka",
      phone: siteSettings.secondaryPhone,
      phoneHref: siteSettings.secondaryPhoneHref,
      email: siteSettings.primaryEmail,
      emailHref: siteSettings.primaryEmailHref,
      hours: "Mon-Fri: 08:00 - 17:00",
      coordinates: { lat: -15.41422, lng: 28.28349 },
      primary: true,
    },
    {
      name: "Copperbelt Regional Office",
      address: "Zambia Bureau of Standards, Kitwe",
      pobox: "P.O. Box 21189, Kitwe",
      phone: "+260 212 226 345",
      phoneHref: "tel:+260212226345",
      email: "kitwe@zabs.org.zm",
      emailHref: "mailto:kitwe@zabs.org.zm",
      hours: "Mon-Fri: 08:00 - 17:00",
      coordinates: { lat: -12.8206, lng: 28.2134 },
      primary: false,
    },
    {
      name: "Livingstone Regional Office",
      address: "Zambia Bureau of Standards, Livingstone",
      pobox: "P.O. Box 60322, Livingstone",
      phone: "+260 213 323 456",
      phoneHref: "tel:+260213323456",
      email: "livingstone@zabs.org.zm",
      emailHref: "mailto:livingstone@zabs.org.zm",
      hours: "Mon-Fri: 08:00 - 17:00",
      coordinates: { lat: -17.8514, lng: 25.8565 },
      primary: false,
    },
  ] satisfies ContactOffice[],
  formSection: {
    badge: "Send Message",
    title: "Send Us a Message",
    description: "Fill in the form and we will respond within 2 business days.",
    formAction: siteSettings.primaryEmailHref,
    subjects: [
      "Standards Enquiry",
      "Certification Enquiry",
      "Testing Enquiry",
      "Training Enquiry",
      "Buy Standards",
      "General Enquiry",
      "Complaint",
    ],
  },
  socialSection: {
    badge: "Connect With Us",
    title: "Follow ZABS",
    description: "Stay updated with our latest news and announcements.",
  },
  socials: [
    {
      name: "Facebook",
      icon: "facebook",
      handle: "@ZambiaBureauofStandards",
      href: "https://facebook.com/zambiastandards",
      colorClass: "bg-[#1877f2]",
      hoverClass: "hover:bg-[#1877f2]/90",
    },
    {
      name: "Twitter",
      icon: "twitter",
      handle: "@ZABS_Zambia",
      href: "#",
      colorClass: "bg-[#1da1f2]",
      hoverClass: "hover:bg-[#1da1f2]/90",
    },
    {
      name: "LinkedIn",
      icon: "linkedin",
      handle: "ZABS Zambia",
      href: "#",
      colorClass: "bg-[#0a66c2]",
      hoverClass: "hover:bg-[#0a66c2]/90",
    },
    {
      name: "YouTube",
      icon: "youtube",
      handle: "ZABS Channel",
      href: "#",
      colorClass: "bg-[#ff0000]",
      hoverClass: "hover:bg-[#ff0000]/90",
    },
  ] satisfies ContactSocialItem[],
  faqPreview: [
    { question: "How do I get my product certified?", label: "How do I get my product certified?", href: "/faq#certification" },
    { question: "What are the testing laboratory hours?", label: "What are the testing laboratory hours?", href: "/faq#testing" },
    { question: "How can I buy Zambia Standards?", label: "How can I buy Zambia Standards?", href: "/faq#standards" },
    { question: "What training courses are available?", label: "What training courses are available?", href: "/faq#training" },
  ] satisfies ContactFaqItem[],
  faqCard: {
    title: "Looking for Quick Answers?",
    description:
      "Check our Frequently Asked Questions page for instant answers to common enquiries.",
    cta: { label: "Visit FAQ Page", href: "/faq" },
  },
  emergencySupport: {
    title: "After Hours Support",
    description:
      "For urgent matters outside office hours, please email us and we will respond promptly.",
    email: "emergency@zabs.org.zm",
    emailHref: "mailto:emergency@zabs.org.zm",
  },
};
