export const buyStandardsPageContent = {
  standards: [
    { id: 1, code: "ZS 117:2022", title: "Wheat Flour -- Specification", category: "Food & Agriculture", price: 350, pages: 24, status: "Current", popular: true, year: "2022" },
    { id: 2, code: "ZS 120:2021", title: "Maize Meal -- Specification", category: "Food & Agriculture", price: 300, pages: 18, status: "Current", popular: true, year: "2021" },
    { id: 3, code: "ZS 148:2020", title: "Drinking Water -- Specification", category: "Environment & Water", price: 400, pages: 32, status: "Current", popular: true, year: "2020" },
    { id: 4, code: "ZS 150:2023", title: "Cement -- Specification", category: "Construction", price: 450, pages: 40, status: "Current", popular: false, year: "2023" },
    { id: 5, code: "ZS 155:2021", title: "Steel Bars for Reinforcement -- Specification", category: "Construction", price: 500, pages: 28, status: "Current", popular: true, year: "2021" },
    { id: 6, code: "ZS 162:2022", title: "Electric Cables -- Specification", category: "Electrical", price: 380, pages: 36, status: "Current", popular: false, year: "2022" },
    { id: 7, code: "ZS 175:2020", title: "Cooking Oil -- Specification", category: "Food & Agriculture", price: 280, pages: 20, status: "Current", popular: true, year: "2020" },
    { id: 8, code: "ZS 180:2021", title: "Bottled Water -- Specification", category: "Environment & Water", price: 320, pages: 22, status: "Current", popular: false, year: "2021" },
    { id: 9, code: "ZS 200:2022", title: "Powdered Milk -- Specification", category: "Food & Agriculture", price: 350, pages: 26, status: "Current", popular: false, year: "2022" },
    { id: 10, code: "ZS 210:2021", title: "Solar Panels -- Performance Requirements", category: "Energy", price: 600, pages: 48, status: "Current", popular: true, year: "2021" },
    { id: 11, code: "ZS 215:2020", title: "Household Electrical Appliances -- Safety", category: "Electrical", price: 420, pages: 38, status: "Current", popular: false, year: "2020" },
    { id: 12, code: "ZS 220:2023", title: "Paints and Varnishes -- Specification", category: "Construction", price: 380, pages: 30, status: "Current", popular: false, year: "2023" },
    { id: 13, code: "ZS 225:2022", title: "Textiles -- Test Methods", category: "Textiles", price: 340, pages: 28, status: "Current", popular: false, year: "2022" },
    { id: 14, code: "ZS 230:2021", title: "Wooden Furniture -- Specification", category: "Manufacturing", price: 360, pages: 24, status: "Current", popular: false, year: "2021" },
    { id: 15, code: "ZS 240:2022", title: "Petroleum Products -- Petrol Specification", category: "Energy", price: 480, pages: 42, status: "Current", popular: true, year: "2022" },
    { id: 16, code: "ZS 245:2021", title: "Petroleum Products -- Diesel Specification", category: "Energy", price: 480, pages: 40, status: "Current", popular: true, year: "2021" },
    { id: 17, code: "ZS 250:2020", title: "Cosmetics -- Safety Requirements", category: "Health & Safety", price: 400, pages: 34, status: "Current", popular: false, year: "2020" },
    { id: 18, code: "ZS 255:2022", title: "Pharmaceutical Products -- Good Manufacturing Practice", category: "Health & Safety", price: 550, pages: 52, status: "Current", popular: false, year: "2022" },
    { id: 19, code: "ZS 260:2021", title: "Construction Aggregates -- Specification", category: "Construction", price: 380, pages: 26, status: "Current", popular: false, year: "2021" },
    { id: 20, code: "ZS 265:2023", title: "Bricks and Blocks -- Specification", category: "Construction", price: 350, pages: 22, status: "Current", popular: false, year: "2023" },
    { id: 21, code: "ZS 270:2022", title: "Sugar -- Specification", category: "Food & Agriculture", price: 300, pages: 18, status: "Current", popular: true, year: "2022" },
    { id: 22, code: "ZS 275:2020", title: "Salt -- Specification", category: "Food & Agriculture", price: 280, pages: 16, status: "Current", popular: false, year: "2020" },
    { id: 23, code: "ZS 280:2021", title: "Fertilisers -- Specification", category: "Food & Agriculture", price: 420, pages: 36, status: "Current", popular: false, year: "2021" },
    { id: 24, code: "ZS 285:2022", title: "Pesticides -- Labelling Requirements", category: "Food & Agriculture", price: 380, pages: 30, status: "Current", popular: false, year: "2022" },
    { id: 25, code: "ZS 290:2021", title: "Fire Extinguishers -- Specification", category: "Health & Safety", price: 440, pages: 38, status: "Current", popular: false, year: "2021" },
    { id: 26, code: "ZS 295:2022", title: "Personal Protective Equipment -- Requirements", category: "Health & Safety", price: 460, pages: 40, status: "Current", popular: false, year: "2022" },
    { id: 27, code: "ZS 300:2020", title: "Motor Vehicle Tyres -- Specification", category: "Automotive", price: 500, pages: 44, status: "Current", popular: true, year: "2020" },
    { id: 28, code: "ZS 305:2021", title: "Lubricating Oils -- Specification", category: "Automotive", price: 420, pages: 36, status: "Current", popular: false, year: "2021" },
    { id: 29, code: "ZS 310:2022", title: "PVC Pipes -- Specification", category: "Construction", price: 380, pages: 28, status: "Current", popular: false, year: "2022" },
    { id: 30, code: "ZS 315:2021", title: "Galvanised Steel Sheets -- Specification", category: "Construction", price: 400, pages: 32, status: "Current", popular: false, year: "2021" },
    { id: 31, code: "ZS 320:2022", title: "Copper Wires and Cables -- Specification", category: "Electrical", price: 450, pages: 38, status: "Current", popular: false, year: "2022" },
    { id: 32, code: "ZS 325:2021", title: "Batteries -- Performance Requirements", category: "Electrical", price: 360, pages: 28, status: "Current", popular: false, year: "2021" },
    { id: 33, code: "ZS 330:2023", title: "Rice -- Specification", category: "Food & Agriculture", price: 300, pages: 20, status: "Current", popular: true, year: "2023" },
    { id: 34, code: "ZS 335:2022", title: "Soya Products -- Specification", category: "Food & Agriculture", price: 320, pages: 22, status: "Current", popular: false, year: "2022" },
    { id: 35, code: "ZS 340:2021", title: "Baby Foods -- Specification", category: "Food & Agriculture", price: 380, pages: 30, status: "Current", popular: false, year: "2021" },
    { id: 36, code: "ZS 345:2022", title: "Meat Products -- Specification", category: "Food & Agriculture", price: 400, pages: 34, status: "Current", popular: false, year: "2022" },
    { id: 37, code: "ZS 350:2020", title: "Fish and Fish Products -- Specification", category: "Food & Agriculture", price: 380, pages: 30, status: "Current", popular: false, year: "2020" },
    { id: 38, code: "ZS 355:2021", title: "Dairy Products -- Yoghurt Specification", category: "Food & Agriculture", price: 320, pages: 22, status: "Current", popular: false, year: "2021" },
    { id: 39, code: "ZS 360:2022", title: "Beverages -- Non-Alcoholic Specification", category: "Food & Agriculture", price: 340, pages: 26, status: "Current", popular: false, year: "2022" },
    { id: 40, code: "ZS 365:2021", title: "Beer -- Specification", category: "Food & Agriculture", price: 360, pages: 28, status: "Current", popular: false, year: "2021" },
    { id: 41, code: "ZS 370:2022", title: "Soap and Detergents -- Specification", category: "Manufacturing", price: 350, pages: 26, status: "Current", popular: false, year: "2022" },
    { id: 42, code: "ZS 375:2021", title: "Candles -- Specification", category: "Manufacturing", price: 280, pages: 16, status: "Current", popular: false, year: "2021" },
    { id: 43, code: "ZS 380:2022", title: "Plastics -- Food Contact Materials", category: "Manufacturing", price: 400, pages: 34, status: "Current", popular: false, year: "2022" },
    { id: 44, code: "ZS 385:2020", title: "Paper and Paper Board -- Specification", category: "Manufacturing", price: 360, pages: 28, status: "Current", popular: false, year: "2020" },
    { id: 45, code: "ZS 390:2021", title: "Healthcare Waste Management", category: "Health & Safety", price: 450, pages: 40, status: "Current", popular: false, year: "2021" },
    { id: 46, code: "ZS 395:2022", title: "Information Technology -- Security", category: "ICT", price: 500, pages: 46, status: "Current", popular: false, year: "2022" },
    { id: 47, code: "ZS 400:2021", title: "Telecommunications Equipment -- Requirements", category: "ICT", price: 480, pages: 42, status: "Current", popular: false, year: "2021" },
    { id: 48, code: "ZS 405:2022", title: "Seeds -- Certification Requirements", category: "Food & Agriculture", price: 400, pages: 34, status: "Current", popular: false, year: "2022" },
    { id: 49, code: "ZS 410:2021", title: "Honey -- Specification", category: "Food & Agriculture", price: 300, pages: 20, status: "Current", popular: true, year: "2021" },
    { id: 50, code: "ZS 415:2022", title: "Charcoal -- Specification", category: "Energy", price: 320, pages: 22, status: "Current", popular: false, year: "2022" },
  ],
  categories: ["All Categories", "Food & Agriculture", "Construction", "Electrical", "Energy", "Health & Safety", "Environment & Water", "Automotive", "Manufacturing", "Textiles", "ICT"],
  categoryColors: {
    "Food & Agriculture": "bg-primary-100 text-primary-800",
    Construction: "bg-secondary-100 text-secondary-800",
    Electrical: "bg-grey-100 text-grey-800",
    Energy: "bg-primary-50 text-primary-700",
    "Health & Safety": "bg-secondary-50 text-secondary-700",
    "Environment & Water": "bg-primary-100 text-primary-800",
    Automotive: "bg-grey-100 text-grey-800",
    Manufacturing: "bg-secondary-100 text-secondary-800",
    Textiles: "bg-grey-50 text-grey-700",
    ICT: "bg-primary-50 text-primary-700",
  } as Record<string, string>,
  stats: [
    { value: "500+", label: "Total Standards", sub: "And growing", icon: "bookOpen" },
    { value: "10", label: "Categories", sub: "Industry sectors", icon: "layers" },
    { value: "48", label: "New This Year", sub: "2024 additions", icon: "trendingUp" },
    { value: "24h", label: "Digital Delivery", sub: "For PDF copies", icon: "clock" },
  ],
  itemsPerPage: 12,
};

export const publicationsPageContent = {
  publicationTypeTabDetails: {
    "Annual Report": {
      id: "annual-reports",
      label: "Annual Reports",
      focus: "Institutional performance, governance, finance, and yearly delivery updates.",
      typicalContent: "Director General reports, audited summaries, programme performance, and annual highlights.",
      access: "Published yearly as PDF reports.",
    },
    Catalogue: {
      id: "catalogue-zambia-standards",
      label: "Catalogue of Zambia Standards",
      focus: "Reference catalogue of published Zambia Standards available to industry and the public.",
      typicalContent: "Standard codes, titles, classifications, and scope references.",
      access: "Maintained as a downloadable catalogue.",
    },
    Newsletter: {
      id: "newsletters",
      label: "Newsletters",
      focus: "Regular communication on standards updates, training opportunities, and public notices.",
      typicalContent: "Quarterly updates, service announcements, upcoming events, and featured programmes.",
      access: "Published periodically for public download.",
    },
    Policy: {
      id: "standards-planning",
      label: "Standards Planning",
      focus: "Priority planning documents that guide standards development and institutional direction.",
      typicalContent: "Strategic plans, work programmes, policy direction, and planning priorities.",
      access: "Published as planning and reference documents.",
    },
    Report: {
      id: "reports",
      label: "Reports",
      focus: "Topical institutional reports and operational publications prepared for public reference.",
      typicalContent: "Surveillance findings, programme updates, enquiry summaries, and technical reporting outputs.",
      access: "Published as downloadable public reference documents.",
    },
    Brochure: {
      id: "brochures",
      label: "Brochures",
      focus: "Service overviews and concise public-facing information materials.",
      typicalContent: "Programme summaries, service guides, application support material, and promotional handouts.",
      access: "Published as lightweight downloadable information documents.",
    },
  } as Record<
    string,
    {
      id: string;
      label: string;
      focus: string;
      typicalContent: string;
      access: string;
    }
  >,
  publications: [
    { id: 1, type: "Annual Report", title: "ZABS Annual Report 2024", year: 2024, size: "4.2 MB", format: "PDF", desc: "Comprehensive report covering ZABS activities, achievements, and financial performance for the year 2024.", pages: 84, downloads: 1245, featured: true },
    { id: 2, type: "Annual Report", title: "ZABS Annual Report 2023", year: 2023, size: "3.8 MB", format: "PDF", desc: "Comprehensive report covering ZABS activities, achievements, and financial performance for the year 2023.", pages: 78, downloads: 982, featured: false },
    { id: 3, type: "Annual Report", title: "ZABS Annual Report 2022", year: 2022, size: "3.5 MB", format: "PDF", desc: "Comprehensive report covering ZABS activities, achievements, and financial performance for the year 2022.", pages: 76, downloads: 856, featured: false },
    { id: 4, type: "Newsletter", title: "ZABS Standards Update - Q4 2024", year: 2024, size: "1.2 MB", format: "PDF", desc: "Quarterly newsletter featuring newly published standards, upcoming training, and industry news.", pages: 16, downloads: 543, featured: true },
    { id: 5, type: "Newsletter", title: "ZABS Standards Update - Q3 2024", year: 2024, size: "1.1 MB", format: "PDF", desc: "Quarterly newsletter featuring newly published standards, upcoming training, and industry news.", pages: 16, downloads: 487, featured: false },
    { id: 6, type: "Newsletter", title: "ZABS Standards Update - Q2 2024", year: 2024, size: "0.9 MB", format: "PDF", desc: "Quarterly newsletter featuring newly published standards, upcoming training, and industry news.", pages: 14, downloads: 421, featured: false },
    { id: 7, type: "Newsletter", title: "ZABS Standards Update - Q1 2024", year: 2024, size: "1.0 MB", format: "PDF", desc: "Quarterly newsletter featuring newly published standards, upcoming training, and industry news.", pages: 14, downloads: 398, featured: false },
    { id: 8, type: "Catalogue", title: "ZS Standards Catalogue 2024", year: 2024, size: "6.5 MB", format: "PDF", desc: "Complete listing of all published Zambia Standards including codes, titles, and scope summaries.", pages: 156, downloads: 2103, featured: true },
    { id: 9, type: "Catalogue", title: "ZS Standards Catalogue 2023", year: 2023, size: "5.9 MB", format: "PDF", desc: "Complete listing of all published Zambia Standards including codes, titles, and scope summaries.", pages: 148, downloads: 1567, featured: false },
    { id: 10, type: "Policy", title: "National Quality Policy 2022-2027", year: 2022, size: "2.1 MB", format: "PDF", desc: "Zambia's national policy framework for quality infrastructure, standardisation, and conformity assessment.", pages: 42, downloads: 634, featured: false },
    { id: 11, type: "Policy", title: "ZABS Strategic Plan 2023-2027", year: 2023, size: "3.2 MB", format: "PDF", desc: "Five-year strategic direction for ZABS, including key performance indicators and milestones.", pages: 56, downloads: 789, featured: true },
    { id: 12, type: "Report", title: "Market Surveillance Report 2024", year: 2024, size: "2.8 MB", format: "PDF", desc: "Results of market surveillance activities covering product compliance across major Zambian markets.", pages: 48, downloads: 432, featured: false },
    { id: 13, type: "Report", title: "WTO/TBT Notification Summary 2024", year: 2024, size: "1.5 MB", format: "PDF", desc: "Summary of WTO Technical Barriers to Trade notifications and enquiry point activities.", pages: 32, downloads: 287, featured: false },
    { id: 14, type: "Brochure", title: "Certification Services Brochure", year: 2024, size: "0.8 MB", format: "PDF", desc: "Overview of ZABS and SADCAS certification programmes, requirements, and benefits.", pages: 12, downloads: 1432, featured: true },
    { id: 15, type: "Brochure", title: "Testing Laboratory Services Brochure", year: 2024, size: "0.7 MB", format: "PDF", desc: "Guide to ZABS laboratory testing services, accreditation scope, and contact information.", pages: 10, downloads: 1256, featured: false },
    { id: 16, type: "Brochure", title: "Training Programme Brochure 2026", year: 2026, size: "1.1 MB", format: "PDF", desc: "Calendar and details of ISO training courses offered by ZABS for 2026.", pages: 24, downloads: 876, featured: false },
  ],
  types: ["All Types", "Annual Report", "Newsletter", "Catalogue", "Policy", "Report", "Brochure"],
  typeIcons: {
    "Annual Report": "barChart2",
    Newsletter: "newspaper",
    Catalogue: "bookOpen",
    Policy: "fileText",
    Report: "barChart2",
    Brochure: "fileText",
  } as Record<string, string>,
  typeColors: {
    "Annual Report": "bg-primary-100 text-primary-800",
    Newsletter: "bg-secondary-100 text-secondary-800",
    Catalogue: "bg-grey-100 text-grey-800",
    Policy: "bg-primary-50 text-primary-700",
    Report: "bg-secondary-50 text-secondary-700",
    Brochure: "bg-grey-50 text-grey-700",
  } as Record<string, string>,
  typeBgColors: {
    "Annual Report": "from-primary-600 to-primary-800",
    Newsletter: "from-secondary-500 to-secondary-700",
    Catalogue: "from-grey-600 to-grey-800",
    Policy: "from-primary-700 to-primary-900",
    Report: "from-secondary-600 to-secondary-800",
    Brochure: "from-primary-500 to-primary-700",
  } as Record<string, string>,
  stats: [
    { value: "100+", label: "Publications", sub: "And growing", icon: "fileText" },
    { value: "6", label: "Content Types", sub: "Annual reports to brochures", icon: "bookOpen" },
    { value: "10,000+", label: "Total Downloads", sub: "Annual average", icon: "trendingUp" },
    { value: "Free", label: "Access", sub: "All publications free", icon: "award" },
  ],
  itemsPerPage: 8,
};

export const careersPageContent = {
  vacancies: [
    {
      id: 1,
      title: "Standards Officer - Food & Agriculture",
      department: "Standards Development",
      type: "Full-time",
      location: "Lusaka",
      closing: "30 June 2026",
      salary: "Competitive",
      experience: "2-3 years",
      requirements: [
        "Bachelor's degree in Food Science, Agriculture, or related field",
        "Minimum 2 years experience in food quality or standards",
        "Knowledge of Codex Alimentarius and ISO standards",
        "Excellent written and verbal communication skills",
        "Strong analytical and problem-solving abilities",
        "Membership in relevant professional body is an added advantage",
      ],
      duties: [
        "Develop and review Zambia Standards in the food and agriculture sector",
        "Participate in technical committee meetings and stakeholder consultations",
        "Liaise with stakeholders in the food industry including producers and regulators",
        "Represent ZABS in regional and international standardisation meetings",
        "Conduct research on emerging food safety issues and technologies",
        "Prepare technical reports and standards documentation",
      ],
    },
    {
      id: 2,
      title: "Laboratory Technician - Chemistry",
      department: "Testing Laboratories",
      type: "Full-time",
      location: "Lusaka",
      closing: "30 June 2026",
      salary: "Competitive",
      experience: "1-2 years",
      requirements: [
        "Diploma or degree in Chemistry or Chemical Engineering",
        "Experience in analytical laboratory work",
        "Familiarity with ISO/IEC 17025 requirements",
        "Strong attention to detail and record-keeping skills",
        "Knowledge of laboratory safety procedures",
        "Experience with HPLC, GC, or AAS is an advantage",
      ],
      duties: [
        "Conduct chemical analysis of samples according to standard methods",
        "Maintain laboratory equipment and calibration records",
        "Prepare test reports and certificates of analysis",
        "Contribute to laboratory quality management activities",
        "Participate in proficiency testing schemes",
        "Ensure compliance with safety and quality protocols",
      ],
    },
    {
      id: 3,
      title: "Certification Officer",
      department: "Certification",
      type: "Full-time",
      location: "Lusaka",
      closing: "15 July 2026",
      salary: "Competitive",
      experience: "3-5 years",
      requirements: [
        "Bachelor's degree in Quality Management, Engineering, or Science",
        "ISO 9001 Lead Auditor certification (preferred)",
        "Minimum 3 years experience in quality systems auditing",
        "Knowledge of SADCAS accreditation requirements",
        "Strong report writing and communication skills",
        "Ability to work independently and manage multiple audits",
      ],
      duties: [
        "Conduct product and management system certification audits",
        "Review certification applications and audit reports",
        "Liaise with applicants and certified organisations",
        "Maintain certification records and surveillance schedules",
        "Participate in assessor calibration and training",
        "Provide technical guidance to certification applicants",
      ],
    },
    {
      id: 4,
      title: "ICT Officer",
      department: "Information Technology",
      type: "Full-time",
      location: "Lusaka",
      closing: "15 July 2026",
      salary: "Competitive",
      experience: "2-3 years",
      requirements: [
        "Bachelor's degree in Computer Science, Information Technology, or related field",
        "Minimum 2 years experience in IT support and systems administration",
        "Proficiency in network management, hardware, and software support",
        "Experience with web-based applications and databases",
        "Knowledge of cybersecurity best practices",
        "Certification in Microsoft, Cisco, or CompTIA is an advantage",
      ],
      duties: [
        "Provide technical support for hardware, software, and networking",
        "Manage ZABS ICT infrastructure and systems",
        "Develop and maintain the ZABS website and internal applications",
        "Implement and monitor cybersecurity measures",
        "Manage user accounts and access permissions",
        "Coordinate with external ICT service providers",
      ],
    },
    {
      id: 5,
      title: "Accounts Assistant",
      department: "Finance",
      type: "Full-time",
      location: "Lusaka",
      closing: "31 July 2026",
      salary: "Competitive",
      experience: "1-2 years",
      requirements: [
        "Diploma or degree in Accounting, Finance, or ACCA Part II",
        "Minimum 2 years experience in accounts payable/receivable",
        "Proficiency in accounting software (Pastel or similar)",
        "Knowledge of Zambian tax regulations and ZPPA procurement procedures",
        "Strong numerical and analytical skills",
        "Membership in ZICA is an added advantage",
      ],
      duties: [
        "Process supplier invoices and staff claims for payment",
        "Prepare monthly bank reconciliations",
        "Maintain the fixed asset register",
        "Assist in preparation of financial reports and budgets",
        "Handle VAT and withholding tax calculations",
        "Support internal and external audit processes",
      ],
    },
  ],
  benefits: [
    { icon: "heart", title: "Health & Wellness", desc: "Comprehensive medical cover for staff and immediate family members including dental and optical benefits.", color: "primary" },
    { icon: "bookOpen", title: "Learning & Development", desc: "Sponsored professional development, training programmes, study leave, and certification support.", color: "secondary" },
    { icon: "award", title: "Recognition Programmes", desc: "Annual staff performance awards, long-service recognition, and employee of the month celebrations.", color: "primary" },
    { icon: "users", title: "Collaborative Culture", desc: "A diverse, inclusive, and supportive working environment with team-building activities.", color: "secondary" },
    { icon: "briefcase", title: "Competitive Remuneration", desc: "Market-related salary packages with performance bonuses and annual increments.", color: "primary" },
    { icon: "clock", title: "Work-Life Balance", desc: "Flexible leave policies, compressed work week options, and a supportive HR framework.", color: "secondary" },
  ],
  coreValues: [
    { value: "Integrity", desc: "We uphold the highest standards of honesty and ethical conduct", icon: "shieldCheck" },
    { value: "Excellence", desc: "We strive for quality and continuous improvement in everything we do", icon: "star" },
    { value: "Innovation", desc: "We embrace new ideas and technologies to improve our services", icon: "sparkles" },
    { value: "Teamwork", desc: "We work collaboratively to achieve our organizational goals", icon: "users" },
    { value: "Respect", desc: "We value diversity and treat everyone with dignity and respect", icon: "smile" },
    { value: "Accountability", desc: "We take ownership and responsibility for our actions", icon: "target" },
  ],
  stats: [
    { value: "100+", label: "Employees", sub: "And growing", icon: "users" },
    { value: "15+", label: "Departments", sub: "Diverse opportunities", icon: "building2" },
    { value: "95%", label: "Employee Satisfaction", sub: "2024 survey", icon: "star" },
    { value: "10+", label: "Training Hours", sub: "Annual average per employee", icon: "graduationCap" },
  ],
  importantNotes: [
    "Only shortlisted candidates will be contacted",
    "ZABS is an equal opportunity employer",
    "Canvassing will lead to automatic disqualification",
  ],
};

export const faqPageContent = {
  faqs: [
    {
      category: "Standards",
      icon: "bookOpen",
      color: "primary",
      items: [
        { q: "What is a Zambia Standard (ZS)?", a: "A Zambia Standard (ZS) is a document established by consensus and approved by ZABS that provides rules, guidelines, or characteristics for activities or their results, aimed at achieving the optimum degree of order in a given context. These standards cover various sectors including food safety, construction, manufacturing, and environmental management." },
        { q: "How are Zambia Standards developed?", a: "Zambia Standards are developed through a transparent consensus-based process involving Technical Committees comprising industry experts, consumer representatives, government agencies, academia, and other stakeholders. The process includes proposal, drafting, public comment, and final approval stages. Each standard undergoes rigorous review before publication." },
        { q: "How can I buy a Zambia Standard?", a: "Zambia Standards can be purchased by contacting the Standards Department at +260 777 764 420 or standards@zabs.org.zm. You can also use the Buy Standards section on our website to browse and request standards. Payment can be made by direct bank transfer or at our offices in Lusaka, Kitwe, or Livingstone." },
        { q: "Can I participate in standards development?", a: "Yes. ZABS welcomes participation from all stakeholders in the standards development process. You can apply to join a Technical Committee relevant to your sector by contacting the Standards Department. Participation is open to industry experts, consumers, government officials, researchers, and other interested parties. Membership is free and open to all." },
        { q: "What is the WTO/TBT Enquiry Point?", a: "The WTO/TBT (Technical Barriers to Trade) Enquiry Point is a service provided by ZABS as Zambia's obligation under the WTO TBT Agreement. It provides information to trading partners about Zambia's technical regulations, standards, and conformity assessment procedures, and notifies the WTO of new measures that may affect international trade." },
        { q: "How often are standards reviewed?", a: "All Zambia Standards are reviewed every five years to ensure they remain current and relevant. Standards may be confirmed, revised, or withdrawn based on the review outcomes and stakeholder input." },
      ],
    },
    {
      category: "Certification",
      icon: "shieldCheck",
      color: "secondary",
      items: [
        { q: "What types of certification does ZABS offer?", a: "ZABS offers Product Certification (including SADCAS-accredited and non-accredited schemes, EcoMark, and CLSS), Management System Certification (ISO 9001, ISO 14001, ISO 45001, ISO 22000, ISO/IEC 17025, ISO 55001, ISO 37001, ISO 27001, ISO 50001, and ISO 22301), and other conformity assessment services. Each scheme has specific requirements and benefits." },
        { q: "What is SADCAS?", a: "SADCAS (Southern African Development Community Accreditation Service) is the accreditation body for the SADC region. ZABS is accredited by SADCAS to offer certain product certification and management system certification schemes, giving our certificates regional and international recognition across all SADC member states." },
        { q: "How long does the certification process take?", a: "The duration depends on the type of certification and the applicant's readiness. Product certification typically takes 4-12 weeks from application to certificate issuance. Management system certification involves an initial audit and may take 2-6 months. ZABS works efficiently to minimise delays once all documentation and samples are received." },
        { q: "What is EcoMark certification?", a: "EcoMark is an eco-labelling scheme that certifies products meeting environmental standards beyond basic legal requirements. It signals to consumers that the product has a reduced environmental impact throughout its lifecycle. Products bearing the EcoMark meet specific criteria for resource efficiency, emissions reduction, and sustainability practices." },
        { q: "What is the CLSS (Compulsory Local Standards Scheme)?", a: "The Compulsory Local Standards Scheme (CLSS) is a mandatory product certification programme for specific regulated product categories determined by the Zambian government. Manufacturers and importers of these products must obtain CLSS certification before they can be placed on the Zambian market to ensure consumer safety." },
        { q: "How do I apply for certification?", a: "To apply for certification, contact the Certification Department at +260 777 764 421 or certification@zabs.org.zm. Our team will guide you through the application requirements, fees, and process steps specific to your product or management system. You can also download application forms from our publications section." },
      ],
    },
    {
      category: "Testing Laboratories",
      icon: "flaskConical",
      color: "primary",
      items: [
        { q: "What testing services does ZABS offer?", a: "ZABS operates nine specialist laboratories offering testing in: Minerals, Civil & Construction Materials, Solar Energy Products, Petroleum Products, Paints & Coatings, General Chemistry, Microbiology, Condom & Latex Products, and Chromatography (pesticides, aflatoxins). Each laboratory is equipped with state-of-the-art equipment and staffed by qualified scientists." },
        { q: "Is ZABS SADCAS-accredited for testing?", a: "Yes, selected ZABS laboratories are accredited by SADCAS to ISO/IEC 17025, the international standard for testing and calibration laboratories. This accreditation ensures the technical competence of our laboratories and the reliability of our test results, which are accepted across the SADC region." },
        { q: "How do I submit samples for testing?", a: "Contact the Testing Laboratory Department at +260 777 764 423 or testing@zabs.org.zm to discuss your testing needs, receive a quotation, and obtain instructions for sample submission. Samples should be properly labelled, sealed, and accompanied by a completed test request form available on our website." },
        { q: "How long does testing take?", a: "Turnaround times vary depending on the type of test and current laboratory workload. Routine tests typically take 5-10 working days. For urgent requirements, an expedited service may be available at an additional fee. ZABS will provide an estimated turnaround time when you submit your samples." },
        { q: "What is the cost of testing?", a: "Testing costs vary depending on the type of analysis, complexity, and number of samples. Contact our testing department for a detailed quotation. We offer competitive pricing and discounts for bulk sample submissions or long-term service agreements." },
        { q: "Can I get a copy of my test results?", a: "Yes, all test results are provided in a formal test report that includes methodology, results, and interpretation. Reports are issued within 5 working days of test completion and can be sent via email or collected in person." },
      ],
    },
    {
      category: "Training",
      icon: "graduationCap",
      color: "secondary",
      items: [
        { q: "What ISO training courses does ZABS offer?", a: "ZABS offers training on: ISO 9001 (Quality Management), ISO 14001 (Environmental Management), ISO 45001 (Occupational Health & Safety), ISO 22000 (Food Safety), ISO/IEC 17025 (Laboratory Competence), ISO 55001 (Asset Management), ISO 37001 (Anti-Bribery), ISO 22301 (Business Continuity), ISO 27001 (Information Security), ISO 50001 (Energy Management), ISO 30414 (Human Capital Reporting), HACCP/ZS 452, Integrated Management Systems, GAP, GMP, Quality Improvement Tools, Risk Management, and Internal/Lead Auditor courses." },
        { q: "Are ZABS training certificates internationally recognised?", a: "ZABS training certificates are widely recognised by industry and government in Zambia and the SADC region. For internationally accredited certificates (e.g., IRCA-certified Lead Auditor courses), we partner with internationally accredited training providers. Please check the specific course details for accreditation information." },
        { q: "Can ZABS conduct training at my organisation?", a: "Yes. ZABS offers in-house/customised training programmes tailored to your organisation's specific needs, schedule, and number of participants. In-house training is often more cost-effective for groups of 5 or more. Contact the Training Department for a customised quotation and curriculum design." },
        { q: "How do I enrol for a training course?", a: "Contact the Training Department at +260 777 764 421 or training@zabs.org.zm to check upcoming course dates, fees, and availability. Complete the enrolment form, make payment, and attend the course on the scheduled date. Early enrolment is recommended as courses fill up quickly. Group discounts are available." },
        { q: "Do you offer online training?", a: "Yes, selected courses are available in virtual classroom format. Contact the Training Department for current online offerings and technology requirements. Blended learning options combining online and in-person sessions are also available." },
        { q: "What is the cancellation policy?", a: "Cancellations received 14 days before the course date receive a full refund. Cancellations received 7-13 days before receive a 50% refund. Cancellations within 7 days are non-refundable but may be transferred to a future course date." },
      ],
    },
    {
      category: "General",
      icon: "helpCircle",
      color: "primary",
      items: [
        { q: "What is the mandate of ZABS?", a: "ZABS (Zambia Bureau of Standards) was established under the Standards Act Cap 416 of the Laws of Zambia, now replaced by Standards Act No. 4 of 2017. Its mandate includes: developing and publishing national standards; providing testing, calibration, and inspection services; operating product certification schemes; providing management system certification; promoting the use of standards; and representing Zambia in international standardisation bodies such as ISO, IEC, ARSO, and SADCMET." },
        { q: "How can I report a substandard product?", a: "You can report substandard or counterfeit products to ZABS by calling our main line at +260 211 231 987, emailing info@zabs.org.zm, or visiting our offices at Lechwe House, Freedom Way, Lusaka. Provide as much detail as possible including the product name, brand, batch number, where it was purchased, and the nature of the problem. All reports are investigated confidentially." },
        { q: "Does ZABS have regional offices?", a: "Yes, ZABS has regional offices on the Copperbelt (Kitwe) and in Livingstone, in addition to the Head Office in Lusaka. These offices handle local enquiries and some services including standards sales and sample collection. Contact the Head Office for referral to the appropriate regional office for specific services." },
        { q: "How can I become a ZABS member?", a: "ZABS offers membership to individuals, organisations, and companies interested in standards development and quality promotion. Members benefit from discounted standards purchases (up to 30% off), access to technical committee participation, advance notification of new standards, and invitations to ZABS events and workshops. Contact us at info@zabs.org.zm for membership information and fees." },
        { q: "What are ZABS office hours?", a: "ZABS offices are open Monday to Friday from 08:00 to 17:00, excluding public holidays. The Testing Laboratory accepts samples until 15:00 for same-day processing. Regional offices follow the same operating hours." },
        { q: "How do I file a complaint about ZABS services?", a: "ZABS has a formal complaints procedure. Submit your complaint in writing to The Director General at ZABS Head Office or email complaints@zabs.org.zm. You will receive acknowledgement within 48 hours and a resolution within 14 working days. All complaints are handled confidentially and without prejudice." },
      ],
    },
  ],
  categories: ["All", "Standards", "Certification", "Testing Laboratories", "Training", "General"],
  stats: [
    { value: "50+", label: "FAQs Available", sub: "Comprehensive answers", icon: "helpCircle" },
    { value: "5", label: "Categories", sub: "Organised by topic", icon: "bookOpen" },
    { value: "24/7", label: "Online Access", sub: "Always available", icon: "clock" },
    { value: "95%", label: "Resolution Rate", sub: "First contact", icon: "star" },
  ],
};
