import {
  Award,
  BadgeCheck,
  Beaker,
  BookOpen,
  Calendar,
  Clock,
  Cpu,
  Droplets,
  FileText,
  FlaskConical,
  Globe,
  GraduationCap,
  Leaf,
  Phone,
  Microscope,
  ShieldCheck,
  Star,
  Target,
  TestTube,
  TrendingUp,
  Users,
  Zap,
} from "lucide-react";

export const trainingPageContent = {
  courses: [
    { code: "ISO 9001:2015", title: "Quality Management System", category: "QMS", desc: "Understand and implement a quality management system to enhance customer satisfaction.", level: "Foundation to Lead Auditor", duration: "3-5 days", popular: true },
    { code: "ISO 14001:2015", title: "Environmental Management System", category: "EMS", desc: "Implement effective environmental management to reduce environmental impact.", level: "Foundation to Lead Auditor", duration: "3-5 days", popular: true },
    { code: "ISO 45001:2018", title: "Occupational Health and Safety", category: "OHSMS", desc: "Improve workplace safety and reduce occupational health risks.", level: "Foundation to Lead Auditor", duration: "3-5 days", popular: true },
    { code: "ISO 22000:2018", title: "Food Safety Management System", category: "FSMS", desc: "Ensure food safety throughout the supply chain from farm to fork.", level: "Foundation to Lead Auditor", duration: "3-5 days", popular: true },
    { code: "ISO 17025:2017", title: "Laboratory Management System", category: "LMS", desc: "Implement competent laboratory management for testing and calibration.", level: "Foundation to Internal Auditor", duration: "3-5 days", popular: false },
    { code: "ISO 55001:2018", title: "Asset Management System", category: "AMS", desc: "Optimize asset management to deliver organizational objectives.", level: "Foundation", duration: "2-3 days", popular: false },
    { code: "ISO 37001:2016", title: "Anti-bribery Management", category: "ABMS", desc: "Establish anti-bribery controls and comply with anti-corruption requirements.", level: "Foundation", duration: "2 days", popular: false },
    { code: "ISO 22301:2019", title: "Business Continuity Management", category: "BCMS", desc: "Build organizational resilience and capability for effective response to disruptions.", level: "Foundation", duration: "2-3 days", popular: false },
    { code: "ISO 27001:2022", title: "Information Security Management", category: "ISMS", desc: "Protect information assets through systematic risk management.", level: "Foundation to Lead Auditor", duration: "3-5 days", popular: true },
    { code: "ISO 50001:2018", title: "Energy Management System", category: "EnMS", desc: "Improve energy performance including energy efficiency, use, and consumption.", level: "Foundation", duration: "2-3 days", popular: false },
    { code: "ISO 30414", title: "Human Resource Management System", category: "HRMS", desc: "Implement human capital reporting standards for organizational transparency.", level: "Foundation", duration: "2 days", popular: false },
    { code: "ZS 452:2014", title: "HACCP System", category: "HACCP", desc: "Implement Hazard Analysis Critical Control Points for food safety management.", level: "Foundation", duration: "3 days", popular: true },
    { code: "Integrated", title: "Integrated Management Systems", category: "IMS", desc: "Combine multiple ISO management system standards into one unified system.", level: "Advanced", duration: "3-4 days", popular: false },
    { code: "GAP", title: "Good Agriculture Practices", category: "GAP", desc: "Implement best practices for agricultural production and food safety.", level: "Foundation", duration: "2 days", popular: false },
    { code: "GMP", title: "Good Manufacturing Practices", category: "GMP", desc: "Implement prerequisite programmes and good manufacturing practices.", level: "Foundation", duration: "2 days", popular: false },
    { code: "QIT", title: "Quality Improvement Tools and Techniques", category: "QI", desc: "Apply quality tools like 5S, Kaizen, Six Sigma, and statistical process control.", level: "Practitioner", duration: "2-3 days", popular: false },
    { code: "Risk", title: "Risk Management System", category: "Risk", desc: "Implement risk-based thinking and enterprise risk management frameworks.", level: "Foundation", duration: "2 days", popular: false },
    { code: "Auditing", title: "Internal Auditing for ISO Systems", category: "Audit", desc: "Conduct effective internal audits of management systems to ISO 19011.", level: "Internal Auditor", duration: "2-3 days", popular: true },
  ],
  categoryColors: {
    QMS: "bg-primary-100 text-primary-800",
    EMS: "bg-secondary-100 text-secondary-800",
    OHSMS: "bg-grey-100 text-grey-800",
    FSMS: "bg-primary-50 text-primary-700",
    LMS: "bg-secondary-50 text-secondary-700",
    AMS: "bg-grey-50 text-grey-700",
    ABMS: "bg-primary-100 text-primary-800",
    BCMS: "bg-secondary-100 text-secondary-800",
    ISMS: "bg-grey-100 text-grey-800",
    EnMS: "bg-primary-50 text-primary-700",
    HRMS: "bg-secondary-50 text-secondary-700",
    HACCP: "bg-secondary-100 text-secondary-800",
    IMS: "bg-grey-100 text-grey-800",
    GAP: "bg-primary-100 text-primary-800",
    GMP: "bg-secondary-50 text-secondary-700",
    QI: "bg-grey-50 text-grey-700",
    Risk: "bg-primary-50 text-primary-700",
    Audit: "bg-primary-100 text-primary-800",
  } as Record<string, string>,
  trainingFormats: [
    { icon: Users, title: "Group Training", desc: "In-house training at your organisation's premises for your team.", features: ["Cost-effective for groups of 5+", "Customized to your industry", "Flexible scheduling"] },
    { icon: GraduationCap, title: "Public Workshops", desc: "Open enrolment training workshops conducted at ZABS training facilities.", features: ["Network with other professionals", "Regular monthly schedules", "Certificate of attendance"] },
    { icon: Calendar, title: "Customized Programs", desc: "Tailored training programs designed to meet your specific organizational needs.", features: ["Bespoke curriculum", "On-site or off-site delivery", "Industry-specific focus"] },
  ],
  stats: [
    { value: "18+", label: "Training Courses", sub: "ISO management systems", icon: BookOpen },
    { value: "500+", label: "Professionals Trained", sub: "Annually across Zambia", icon: Users },
    { value: "100%", label: "Expert Trainers", sub: "Certified professionals", icon: Award },
    { value: "95%", label: "Satisfaction Rate", sub: "From past participants", icon: Star },
  ],
  testimonials: [
    {
      name: "John Banda",
      role: "Quality Manager",
      company: "Zambia Sugar PLC",
      content: "The ISO 9001 training was exceptional. The facilitators were knowledgeable and practical. I highly recommend ZABS training.",
      rating: 5,
    },
    {
      name: "Mary Phiri",
      role: "Food Safety Officer",
      company: "Zambeef Products",
      content: "The HACCP training gave our team the skills we needed to improve our food safety systems. Very practical and applicable.",
      rating: 5,
    },
    {
      name: "Peter Mwansa",
      role: "Environmental Manager",
      company: "Chilanga Cement",
      content: "Excellent delivery of ISO 14001 training. The case studies and examples were relevant to our Zambian context.",
      rating: 5,
    },
  ],
  steps: [
    { step: "01", title: "Choose Your Course", desc: "Select the ISO management system training that meets your professional or organizational needs.", icon: BookOpen },
    { step: "02", title: "Contact ZABS Training", desc: "Reach out to the Training Department to enquire about upcoming workshop dates or in-house training.", icon: Phone },
    { step: "03", title: "Register & Pay", desc: "Complete the registration form and submit payment to secure your place on the course.", icon: FileText },
    { step: "04", title: "Attend & Certify", desc: "Complete training and receive your ZABS certificate of training attendance.", icon: Award },
  ],
  whyChooseUs: [
    {
      title: "Certified Trainers",
      desc: "All trainers are certified professionals with extensive industry experience.",
      icon: BadgeCheck,
      color: "primary",
    },
    {
      title: "Practical Approach",
      desc: "Case studies and examples relevant to the Zambian context.",
      icon: Target,
      color: "secondary",
    },
    {
      title: "Recognized Certification",
      desc: "ZABS certificates are widely recognized by employers.",
      icon: Award,
      color: "primary",
    },
    {
      title: "Flexible Delivery",
      desc: "In-house, public, and customized training options available.",
      icon: Calendar,
      color: "secondary",
    },
  ],
};

export const certificationPageContent = {
  managementSystemsData: [
    { company: "Zambia Sugar PLC", standard: "ISO 9001:2015", scope: "Sugar Processing", location: "Mazabuka", status: "Active" },
    { company: "Chilanga Cement PLC", standard: "ISO 14001:2015", scope: "Cement Manufacturing", location: "Chilanga", status: "Active" },
    { company: "ZESCO Limited", standard: "ISO 9001:2015", scope: "Electricity Distribution", location: "Lusaka", status: "Active" },
    { company: "NFC Africa Mining PLC", standard: "ISO 45001:2018", scope: "Copper Mining", location: "Kitwe", status: "Active" },
    { company: "Zambeef Products PLC", standard: "ISO 22000:2018", scope: "Food Processing", location: "Lusaka", status: "Active" },
    { company: "Madison Life Insurance", standard: "ISO 9001:2015", scope: "Insurance Services", location: "Lusaka", status: "Active" },
    { company: "First National Bank Zambia", standard: "ISO 27001:2022", scope: "Banking Services", location: "Lusaka", status: "Active" },
    { company: "Lafarge Zambia PLC", standard: "ISO 14001:2015", scope: "Cement Manufacturing", location: "Lusaka", status: "Active" },
    { company: "Mopani Copper Mines", standard: "ISO 45001:2018", scope: "Copper Mining", location: "Kitwe", status: "Active" },
    { company: "Swarp Spinning Mills", standard: "ISO 9001:2015", scope: "Textile Manufacturing", location: "Livingstone", status: "Active" },
    { company: "National Pension Scheme Authority", standard: "ISO 9001:2015", scope: "Pension Services", location: "Lusaka", status: "Active" },
    { company: "Airtel Zambia", standard: "ISO 27001:2022", scope: "Telecommunications", location: "Lusaka", status: "Active" },
    { company: "MTN Zambia", standard: "ISO 9001:2015", scope: "Telecommunications", location: "Lusaka", status: "Active" },
    { company: "Atlas Mara Zambia", standard: "ISO 9001:2015", scope: "Banking Services", location: "Lusaka", status: "Active" },
    { company: "Copperbelt Energy Corporation", standard: "ISO 14001:2015", scope: "Energy Services", location: "Kitwe", status: "Active" },
  ],
  productsData: [
    { company: "National Milling Company", product: "Roller Meal (Mealie Meal)", category: "Food & Beverages", location: "Lusaka", status: "Active" },
    { company: "Zambia Breweries PLC", product: "Mosi Lager Beer", category: "Food & Beverages", location: "Lusaka", status: "Active" },
    { company: "Lusaka Packaging Ltd", product: "Plastic Containers", category: "Packaging", location: "Lusaka", status: "Active" },
    { company: "Chilanga Cement PLC", product: "Portland Cement OPC 42.5N", category: "Construction", location: "Chilanga", status: "Active" },
    { company: "Zambia Steel Works", product: "Steel Bars & Rods", category: "Construction", location: "Kabwe", status: "Active" },
    { company: "Parmalat Zambia", product: "Pasteurized Milk", category: "Food & Beverages", location: "Lusaka", status: "Active" },
    { company: "Premium Edible Oils", product: "Cooking Oil", category: "Food & Beverages", location: "Ndola", status: "Active" },
    { company: "Solwezi Soap Industries", product: "Laundry Soap", category: "Soaps & Detergents", location: "Solwezi", status: "Active" },
    { company: "Zambezi Paints Ltd", product: "Interior Emulsion Paint", category: "Paints & Coatings", location: "Lusaka", status: "Active" },
    { company: "Total Petroleum Zambia", product: "Diesel Fuel", category: "Petroleum", location: "Lusaka", status: "Active" },
    { company: "Zambeef Products", product: "Sausages", category: "Food & Beverages", location: "Lusaka", status: "Active" },
    { company: "Novatek Chemicals", product: "Agricultural Pesticides", category: "Agriculture", location: "Kafue", status: "Active" },
    { company: "Kafue Textiles", product: "Cotton Fabric", category: "Textiles", location: "Kafue", status: "Active" },
    { company: "Vitafoam Zambia", product: "Foam Mattresses", category: "Consumer Products", location: "Lusaka", status: "Active" },
    { company: "Mpongwe Milling", product: "Refined Wheat Flour", category: "Food & Beverages", location: "Mpongwe", status: "Active" },
  ],
  tabs: [
    { id: 0, label: "Management Systems", sublabel: "ZABS Accredited", icon: "building2" },
    { id: 1, label: "Management Systems", sublabel: "SADCAS Accredited", icon: "globe" },
    { id: 2, label: "Certified Products", sublabel: "SADCAS Accredited", icon: "shieldCheck" },
    { id: 3, label: "Certified Products", sublabel: "Non-Accredited", icon: "fileCheck" },
    { id: 4, label: "EcoMark", sublabel: "Certified Products", icon: "leaf" },
    { id: 5, label: "CLSS", sublabel: "Certified Products", icon: "badgeCheck" },
  ],
  certificationSchemes: [
    {
      icon: "shieldCheck",
      title: "Product Certification",
      desc: "Certification that a product meets Zambian National Standards, verified through periodic testing and audit.",
      tag: "ZS Mark",
      color: "primary",
      features: ["Rigorous testing protocols", "Regular surveillance audits", "Consumer protection assurance"],
    },
    {
      icon: "building2",
      title: "Management Systems",
      desc: "Certification of Quality, Environmental, and Safety management systems against ISO standards.",
      tag: "ISO Certified",
      color: "secondary",
      features: ["ISO 9001, 14001, 45001, etc.", "SADCAS accredited", "International recognition"],
    },
    {
      icon: "leaf",
      title: "EcoMark Certification",
      desc: "Environmental certification for products demonstrating reduced environmental impact throughout their lifecycle.",
      tag: "EcoMark",
      color: "primary",
      features: ["Environmental compliance", "Sustainable practices", "Consumer eco-label"],
    },
    {
      icon: "badgeCheck",
      title: "CLSS Certification",
      desc: "Certification under the Conformity of Locally Sourced and Subsidised Scheme.",
      tag: "CLSS",
      color: "secondary",
      features: ["Local content verification", "Quality assurance", "Market access"],
    },
  ],
  productCategories: [
    "Food and Beverages",
    "Soaps and Detergents",
    "Construction Materials",
    "Textile & Paints",
    "Petroleum Products",
    "Agriculture Products",
    "Electrical Equipment",
    "Personal Protective Equipment",
  ],
  stats: [
    { value: "150+", label: "Certified Products", sub: "Across all sectors", icon: "shieldCheck" },
    { value: "50+", label: "Certified Companies", sub: "Nationwide", icon: "building2" },
    { value: "15+", label: "ISO Standards", sub: "Management systems", icon: "globe" },
    { value: "100%", label: "SADCAS Accredited", sub: "Certification schemes", icon: "award" },
  ],
  benefits: [
    { title: "Market Access", desc: "Certified products gain preference in government procurement and retail markets.", icon: "globe", color: "primary" },
    { title: "Consumer Trust", desc: "The ZABS Quality Mark signals quality and safety to consumers.", icon: "shieldCheck", color: "secondary" },
    { title: "Competitive Edge", desc: "Stand out from competitors with recognized certification.", icon: "trophy", color: "primary" },
    { title: "Export Readiness", desc: "SADCAS accreditation enables regional and international market access.", icon: "building2", color: "secondary" },
    { title: "Process Improvement", desc: "Certification drives internal quality improvements.", icon: "trendingUp", color: "primary" },
    { title: "Legal Compliance", desc: "Meet regulatory requirements for compulsory standards.", icon: "fileCheck", color: "secondary" },
  ],
  itemsPerPage: 10,
};

export const testingPageContent = {
  laboratories: [
    { name: "Minerals Laboratory", icon: Cpu, desc: "Analysis of geological samples, minerals, concentrates, and copper cathodes including soil samples.", capabilities: ["XRF Analysis", "Atomic Absorption", "Fire Assay", "Mineralogy"], accreditation: "SADCAS Accredited", color: "primary" },
    { name: "Civils & Construction Materials", icon: FlaskConical, desc: "Testing of concrete, concrete blocks, building materials, and civil engineering materials.", capabilities: ["Compression Testing", "Tensile Strength", "Density Analysis", "Durability Tests"], accreditation: "SADCAS Accredited", color: "secondary" },
    { name: "Solar Laboratory", icon: Zap, desc: "Testing of solar panels, batteries, and related renewable energy equipment and components.", capabilities: ["PV Module Testing", "Battery Testing", "Performance Analysis", "Durability Testing"], accreditation: "ISO/IEC 17025", color: "primary" },
    { name: "Petroleum (Fuels) Laboratory", icon: Leaf, desc: "Testing of petroleum fuels, lubricants, and related petroleum products for quality and safety.", capabilities: ["Octane Rating", "Viscosity Testing", "Flash Point", "Distillation"], accreditation: "SADCAS Accredited", color: "secondary" },
    { name: "Paint Testing Laboratory", icon: Beaker, desc: "Analysis and testing of paints, coatings, and related chemical products to relevant standards.", capabilities: ["Viscosity Testing", "Adhesion Tests", "Chemical Resistance", "Color Analysis"], accreditation: "ISO/IEC 17025", color: "primary" },
    { name: "General Chemistry Laboratory", icon: Microscope, desc: "General analytical chemistry services including food safety and agricultural inputs testing.", capabilities: ["Wet Chemistry", "Spectrophotometry", "Titrations", "pH Analysis"], accreditation: "SADCAS Accredited", color: "secondary" },
    { name: "Microbiology Laboratory", icon: Microscope, desc: "Microbiological testing for food products, water, and environmental samples for pathogen detection.", capabilities: ["Pathogen Detection", "Total Plate Count", "Water Quality", "Food Safety"], accreditation: "SADCAS Accredited", color: "primary" },
    { name: "Condom & Latex Gloves Testing", icon: TestTube, desc: "Physical, chemical, and microbiological testing of condoms and latex gloves to WHO/ISO standards.", capabilities: ["Air Burst Test", "Water Leak Test", "Tensile Testing", "Microbial Limits"], accreditation: "WHO Pre-qualified", color: "secondary" },
    { name: "Chromatography Laboratory", icon: Droplets, desc: "Gas chromatography and HPLC analysis for complex chemical characterization and food safety.", capabilities: ["GC-MS Analysis", "HPLC", "Pesticide Residues", "Aflatoxin Testing"], accreditation: "ISO/IEC 17025", color: "primary" },
  ],
  clientSectors: [
    { title: "Mining & Extractive Industries", desc: "Geological, Concentrates, Copper Cathodes including soil samples.", icon: Cpu, color: "primary" },
    { title: "Energy & Petroleum", desc: "Industrial Electrical, Solar Panels, Light Bulbs, Electric Cables and General Household Appliances.", icon: Zap, color: "secondary" },
    { title: "Construction", desc: "Construction Materials, Concrete and Concrete Blocks.", icon: FlaskConical, color: "primary" },
    { title: "Textiles & PPE", desc: "Textile, Fabric, Packaging materials, Personal Protective Equipment, Footwear and Paints.", icon: Users, color: "secondary" },
    { title: "Food & Non-Food", desc: "Food and Non-Food Processors and Producers across all categories.", icon: Leaf, color: "primary" },
    { title: "Agriculture", desc: "Agricultural inputs, produce, fertilizers, and related products.", icon: TestTube, color: "secondary" },
  ],
  stats: [
    { value: "9", label: "Specialized Laboratories", sub: "State-of-the-art facilities", icon: FlaskConical },
    { value: "1000+", label: "Tests Performed Annually", sub: "And growing", icon: Microscope },
    { value: "100%", label: "Accredited Services", sub: "ISO/IEC 17025", icon: Award },
    { value: "48h", label: "Rapid Turnaround", sub: "For urgent tests", icon: Clock },
  ],
  testTypes: [
    { name: "Chemical Analysis", desc: "Determination of chemical composition and properties" },
    { name: "Microbiological Testing", desc: "Detection of pathogens and microbial contamination" },
    { name: "Physical Testing", desc: "Mechanical and physical property evaluation" },
    { name: "Environmental Testing", desc: "Water, soil, and air quality analysis" },
    { name: "Food Safety Testing", desc: "Contaminants, additives, and nutritional analysis" },
    { name: "Material Characterization", desc: "Identification and qualification of materials" },
  ],
  features: [
    { title: "Modern Equipment", desc: "State-of-the-art laboratory equipment ensuring accurate, reliable test results.", icon: Microscope, color: "primary" },
    { title: "Qualified Staff", desc: "Highly competent and qualified scientists and technicians handling all analyses.", icon: Users, color: "secondary" },
    { title: "Quality Management", desc: "Laboratory operations implement a quality management system based on ISO 17025.", icon: Award, color: "primary" },
  ],
  qualityAssuranceItems: [
    "Regular proficiency testing and inter-laboratory comparisons",
    "Continuous staff training and competency assessment",
    "Traceable measurements to international standards",
    "Comprehensive quality documentation and audit trails",
  ],
};

export const standardsDevelopmentPageContent = {
  processSteps: [
    { step: "01", title: "Proposal Stage", desc: "A new work item proposal (NWIP) is submitted and evaluated by the relevant Technical Committee (TC).", duration: "1-2 months", icon: FileText },
    { step: "02", title: "Preparatory Stage", desc: "A working group is established to prepare a working draft (WD) of the standard.", duration: "2-3 months", icon: Users },
    { step: "03", title: "Committee Stage", desc: "The working draft is circulated to committee members for comment and revision.", duration: "2-4 months", icon: BookOpen },
    { step: "04", title: "Enquiry Stage", desc: "The draft standard is published for public enquiry and comments from all stakeholders.", duration: "2 months", icon: Globe },
    { step: "05", title: "Approval Stage", desc: "Comments are reviewed, final draft is prepared, and the standard is approved for publication.", duration: "1-2 months", icon: ShieldCheck },
    { step: "06", title: "Publication Stage", desc: "The approved standard is published as a Zambian National Standard (ZS) and made available.", duration: "1 month", icon: Award },
  ],
  enquiryServices: [
    "Sale of Zambian, International and Foreign Standards.",
    "Information on technical specifications to manufacturers and traders.",
    "Information relating to National and International Standards.",
    "Information to exporters on technical regulations of importing countries.",
    "Information on Zambian certified products and services.",
    "National enquiry point (NEP) for Technical Barriers to Trade (WTO/TBT) information.",
  ],
  benefits: [
    { icon: TrendingUp, title: "Promotes Trade", desc: "Standards facilitate domestic and international trade by creating common technical requirements.", color: "primary" },
    { icon: Users, title: "Protects Consumers", desc: "Standards ensure products meet minimum safety and quality requirements protecting consumers.", color: "secondary" },
    { icon: Globe, title: "Enables Exports", desc: "Alignment with international standards helps Zambian products access global markets.", color: "primary" },
    { icon: TrendingUp, title: "Drives Innovation", desc: "Standards provide a foundation for innovation while ensuring interoperability and safety.", color: "secondary" },
  ],
  technicalCommittees: [
    { name: "Food and Agriculture", members: 25, sector: "Agriculture" },
    { name: "Building and Civil Engineering", members: 20, sector: "Construction" },
    { name: "Electrical Engineering", members: 18, sector: "Energy" },
    { name: "Chemical Industries", members: 22, sector: "Manufacturing" },
    { name: "Textiles and Leather", members: 15, sector: "Textiles" },
    { name: "Mining and Metallurgy", members: 28, sector: "Mining" },
    { name: "Environmental Management", members: 20, sector: "Environment" },
    { name: "Information Technology", members: 16, sector: "Technology" },
    { name: "Health and Safety", members: 24, sector: "Healthcare" },
  ],
  keyStats: [
    { value: "500+", label: "Standards Published", sub: "Zambian National Standards", icon: FileText },
    { value: "20+", label: "Technical Committees", sub: "Industry sector coverage", icon: Users },
    { value: "150+", label: "Active Members", sub: "Industry experts", icon: GraduationCap },
    { value: "50+", label: "International Standards", sub: "Adopted as ZS", icon: Globe },
  ],
  internationalBodies: [
    { name: "ISO", description: "International Organization for Standardization", icon: Globe },
    { name: "IEC", description: "International Electrotechnical Commission", icon: Zap },
    { name: "ARSO", description: "African Organisation for Standardisation", icon: Users },
    { name: "SADCSTAN", description: "SADC Standards Organization", icon: Target },
  ],
};
